services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/keys:/config/keys
      - ./nginx/config:/config/nginx
      - ./nginx/logs:/config/log/nginx
    environment:
      - PUID=${PID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
networks: {}
